// Code generated by middlegen. DO NOT EDIT.
package greeter

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"log/slog"
)

func ServiceLoggingMiddleware() middleware.Middleware[Service] {
	logger := slog.Default().With(slog.String("service", "greeter"))
	return func(next Service) Service {
		return &serviceLoggingService{Service: next, next: next, logger: logger}
	}
}

type serviceLoggingService struct {
	Service // forwards methods that cannot be decorated
	next    Service
	logger  *slog.Logger
}

func (l *serviceLoggingService) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	l.logger.DebugContext(ctx, "Greet started", slog.Any("req", req))
	r0, err := l.next.Greet(ctx, req)
	if err != nil {
		l.logger.ErrorContext(ctx, "Greet failed", slog.Any("error", err))
	}
	return r0, err
}
