// Code generated by middlegen. DO NOT EDIT.
package greeter

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func ServiceTracingMiddleware() middleware.Middleware[Service] {
	tracer := otel.Tracer("greeter")
	return func(next Service) Service {
		return &serviceTracingService{Service: next, next: next, tracer: tracer}
	}
}

type serviceTracingService struct {
	Service // forwards methods that cannot be decorated
	next    Service
	tracer  trace.Tracer
}

func (t *serviceTracingService) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	ctx, span := t.tracer.Start(ctx, "greeter.Greet", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.Greet(ctx, req)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}
