// Code generated by middlegen. DO NOT EDIT.
package svcmw

import (
	"context"
	"github.com/pobochiigo/silo/examples/middlegen/inventory"
	"github.com/pobochiigo/silo/middleware"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func ServiceTracingMiddleware() middleware.Middleware[inventory.Service] {
	tracer := otel.Tracer("inventory")
	return func(next inventory.Service) inventory.Service {
		return &serviceTracingService{Service: next, next: next, tracer: tracer}
	}
}

type serviceTracingService struct {
	inventory.Service // forwards methods that cannot be decorated
	next              inventory.Service
	tracer            trace.Tracer
}

func (t *serviceTracingService) Restock(ctx context.Context, sku string, qty int) (*inventory.Item, error) {
	ctx, span := t.tracer.Start(ctx, "inventory.Restock", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.Restock(ctx, sku, qty)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *serviceTracingService) Reserve(ctx context.Context, sku string, qty int) error {
	ctx, span := t.tracer.Start(ctx, "inventory.Reserve", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	err := t.next.Reserve(ctx, sku, qty)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return err
}

func (t *serviceTracingService) Rotate(ctx context.Context, sku string, key string) error {
	ctx, span := t.tracer.Start(ctx, "inventory.Rotate", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	err := t.next.Rotate(ctx, sku, key)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return err
}
