// Code generated by middlegen. DO NOT EDIT.
package svcmw

import (
	"context"

	"github.com/pobochiigo/silo/examples/middlegen/inventory"
	"github.com/pobochiigo/silo/middleware"
	"github.com/pobochiigo/silo/uow"
)

func ServiceUoWMiddleware(manager *uow.Manager) middleware.Middleware[inventory.Service] {
	return func(next inventory.Service) inventory.Service {
		return &serviceUoWMiddleware{Service: next, next: next, manager: manager}
	}
}

type serviceUoWMiddleware struct {
	inventory.Service // forwards methods that cannot be decorated
	next              inventory.Service
	manager           *uow.Manager
}

func (m *serviceUoWMiddleware) Restock(ctx context.Context, sku string, qty int) (*inventory.Item, error) {
	var (
		r0  *inventory.Item
		err error
	)
	err = m.manager.RunWith(ctx, func(uowCtx context.Context) error {
		var innerErr error
		r0, innerErr = m.next.Restock(uowCtx, sku, qty)
		return innerErr
	})
	return r0, err
}

func (m *serviceUoWMiddleware) Reserve(ctx context.Context, sku string, qty int) error {
	return m.manager.RunInTx(ctx, func(uowCtx context.Context) error {
		return m.next.Reserve(uowCtx, sku, qty)
	})
}

func (m *serviceUoWMiddleware) Rotate(ctx context.Context, sku string, key string) error {
	return m.manager.RunWith(ctx, func(uowCtx context.Context) error {
		return m.next.Rotate(uowCtx, sku, key)
	})
}
