// Code generated by middlegen. DO NOT EDIT.
package svcmw

import (
	"context"
	"github.com/pobochiigo/silo/examples/middlegen/inventory"
	"github.com/pobochiigo/silo/middleware"
	"log/slog"
)

func ServiceLoggingMiddleware() middleware.Middleware[inventory.Service] {
	logger := slog.Default().With(slog.String("service", "inventory"))
	return func(next inventory.Service) inventory.Service {
		return &serviceLoggingService{Service: next, next: next, logger: logger}
	}
}

type serviceLoggingService struct {
	inventory.Service // forwards methods that cannot be decorated
	next              inventory.Service
	logger            *slog.Logger
}

func (l *serviceLoggingService) Restock(ctx context.Context, sku string, qty int) (*inventory.Item, error) {
	l.logger.DebugContext(ctx, "Restock started", slog.Any("sku", sku), slog.Any("qty", qty))
	r0, err := l.next.Restock(ctx, sku, qty)
	if err != nil {
		l.logger.ErrorContext(ctx, "Restock failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *serviceLoggingService) Reserve(ctx context.Context, sku string, qty int) error {
	l.logger.DebugContext(ctx, "Reserve started", slog.Any("sku", sku), slog.Any("qty", qty))
	err := l.next.Reserve(ctx, sku, qty)
	if err != nil {
		l.logger.ErrorContext(ctx, "Reserve failed", slog.Any("error", err))
	}
	return err
}

func (l *serviceLoggingService) Rotate(ctx context.Context, sku string, key string) error {
	l.logger.DebugContext(ctx, "Rotate started", slog.Any("sku", sku), slog.Any("key", key))
	err := l.next.Rotate(ctx, sku, key)
	if err != nil {
		l.logger.ErrorContext(ctx, "Rotate failed", slog.Any("error", err))
	}
	return err
}
