// Code generated by middlegen. DO NOT EDIT.
package inventory

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func RepositoryTracingMiddleware() middleware.Middleware[Repository] {
	tracer := otel.Tracer("inventory")
	return func(next Repository) Repository {
		return &repositoryTracingService{Repository: next, next: next, tracer: tracer}
	}
}

type repositoryTracingService struct {
	Repository // forwards methods that cannot be decorated
	next       Repository
	tracer     trace.Tracer
}

func (t *repositoryTracingService) Close() error {
	err := t.next.Close()
	return err
}

func (t *repositoryTracingService) Get(ctx context.Context, sku string) (*Item, error) {
	ctx, span := t.tracer.Start(ctx, "inventory.Get", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.Get(ctx, sku)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) List(ctx context.Context) ([]Item, error) {
	ctx, span := t.tracer.Start(ctx, "inventory.List", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.List(ctx)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) Save(ctx context.Context, item *Item) (*Item, error) {
	ctx, span := t.tracer.Start(ctx, "inventory.Save", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.Save(ctx, item)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) Merge(ctx context.Context, from *Item, into *Item) (*Item, error) {
	ctx, span := t.tracer.Start(ctx, "inventory.Merge", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.Merge(ctx, from, into)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) Archive(ctx context.Context, item *Item) (*Item, error) {
	ctx, span := t.tracer.Start(ctx, "inventory.Archive", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.Archive(ctx, item)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) RotateKey(ctx context.Context, sku string, key string) error {
	ctx, span := t.tracer.Start(ctx, "inventory.RotateKey", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	err := t.next.RotateKey(ctx, sku, key)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return err
}

func (t *repositoryTracingService) Decrement(ctx context.Context, sku string, qty int) (int, error) {
	ctx, span := t.tracer.Start(ctx, "inventory.Decrement", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.Decrement(ctx, sku, qty)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}
