// Code generated by middlegen. DO NOT EDIT.
package inventory

import (
	"context"
	"fmt"
	"time"

	"github.com/pobochiigo/silo/middleware"
	"github.com/pobochiigo/silo/telemetry"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

func RepositoryMetricsMiddleware() middleware.Middleware[Repository] {
	meter := otel.GetMeterProvider().Meter("inventory")
	recorder := telemetry.NewMetricsRecorder(meter, "repository")
	inventorySavesTotalCounter, err := recorder.Meter().Int64Counter("inventory_saves_total", metric.WithDescription("Custom counter for inventory_saves_total"))
	if err != nil {
		otel.Handle(err)
	}
	return func(next Repository) Repository {
		return &repositoryMetricsService{
			Repository:                 next,
			next:                       next,
			recorder:                   recorder,
			inventorySavesTotalCounter: inventorySavesTotalCounter,
		}
	}
}

type repositoryMetricsService struct {
	Repository                 // forwards methods that cannot be decorated
	next                       Repository
	recorder                   *telemetry.MetricsRecorder
	inventorySavesTotalCounter metric.Int64Counter
}

func (m *repositoryMetricsService) Close() error {
	ctx := context.Background()
	now := time.Now()
	err := m.next.Close()
	m.recorder.Observe(ctx, "Close", now, err)
	return err
}

func (m *repositoryMetricsService) Get(ctx context.Context, sku string) (*Item, error) {
	now := time.Now()
	r0, err := m.next.Get(ctx, sku)
	m.recorder.Observe(ctx, "Get", now, err)
	return r0, err
}

func (m *repositoryMetricsService) List(ctx context.Context) ([]Item, error) {
	now := time.Now()
	r0, err := m.next.List(ctx)
	m.recorder.Observe(ctx, "List", now, err)
	return r0, err
}

func (m *repositoryMetricsService) Save(ctx context.Context, item *Item) (*Item, error) {
	now := time.Now()
	m.inventorySavesTotalCounter.Add(ctx, 1)
	r0, err := m.next.Save(ctx, item)
	m.recorder.Observe(ctx, "Save", now, err, attribute.String("stock", fmt.Sprintf("%v", stockOf(item))))
	return r0, err
}

func (m *repositoryMetricsService) Merge(ctx context.Context, from *Item, into *Item) (*Item, error) {
	now := time.Now()
	r0, err := m.next.Merge(ctx, from, into)
	m.recorder.Observe(ctx, "Merge", now, err)
	return r0, err
}

func (m *repositoryMetricsService) Archive(ctx context.Context, item *Item) (*Item, error) {
	now := time.Now()
	r0, err := m.next.Archive(ctx, item)
	m.recorder.Observe(ctx, "Archive", now, err)
	return r0, err
}

func (m *repositoryMetricsService) RotateKey(ctx context.Context, sku string, key string) error {
	now := time.Now()
	err := m.next.RotateKey(ctx, sku, key)
	m.recorder.Observe(ctx, "RotateKey", now, err)
	return err
}

func (m *repositoryMetricsService) Decrement(ctx context.Context, sku string, qty int) (int, error) {
	now := time.Now()
	r0, err := m.next.Decrement(ctx, sku, qty)
	m.recorder.Observe(ctx, "Decrement", now, err)
	return r0, err
}
