// Code generated by middlegen. DO NOT EDIT.
package inventory

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"github.com/pobochiigo/silo/uow"
)

func RepositoryUoWMiddleware() middleware.Middleware[Repository] {
	return func(next Repository) Repository {
		return &repositoryUoWMiddleware{Repository: next, next: next}
	}
}

type repositoryUoWMiddleware struct {
	Repository // forwards methods that cannot be decorated
	next       Repository
}

func (m *repositoryUoWMiddleware) Close() error {
	return m.next.Close()
}

func (m *repositoryUoWMiddleware) Get(ctx context.Context, sku string) (*Item, error) {
	return m.next.Get(ctx, sku)
}

func (m *repositoryUoWMiddleware) List(ctx context.Context) ([]Item, error) {
	return m.next.List(ctx)
}

func (m *repositoryUoWMiddleware) Save(ctx context.Context, item *Item) (*Item, error) {
	if uowInstance, ok := uow.Extract(ctx); ok {
		uowInstance.Defer(func(txCtx context.Context) error {
			_, err := m.next.Save(txCtx, item)
			return err
		})
		return item, nil
	}
	return m.next.Save(ctx, item)
}

func (m *repositoryUoWMiddleware) Merge(ctx context.Context, from *Item, into *Item) (*Item, error) {
	if uowInstance, ok := uow.Extract(ctx); ok {
		uowInstance.Defer(func(txCtx context.Context) error {
			_, err := m.next.Merge(txCtx, from, into)
			return err
		})
		return into, nil
	}
	return m.next.Merge(ctx, from, into)
}

func (m *repositoryUoWMiddleware) Archive(ctx context.Context, item *Item) (*Item, error) {
	if uowInstance, ok := uow.Extract(ctx); ok {
		uowInstance.Defer(func(txCtx context.Context) error {
			_, err := m.next.Archive(txCtx, item)
			return err
		})
		return nil, nil
	}
	return m.next.Archive(ctx, item)
}

func (m *repositoryUoWMiddleware) RotateKey(ctx context.Context, sku string, key string) error {
	if uowInstance, ok := uow.Extract(ctx); ok {
		uowInstance.Defer(func(txCtx context.Context) error {
			return m.next.RotateKey(txCtx, sku, key)
		})
		return nil
	}
	return m.next.RotateKey(ctx, sku, key)
}

func (m *repositoryUoWMiddleware) Decrement(ctx context.Context, sku string, qty int) (int, error) {
	if uowInstance, ok := uow.Extract(ctx); ok {
		uowInstance.Defer(func(txCtx context.Context) error {
			_, err := m.next.Decrement(txCtx, sku, qty)
			return err
		})
		return 0, nil
	}
	return m.next.Decrement(ctx, sku, qty)
}
