// Code generated by middlegen. DO NOT EDIT.
package inventory

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"log/slog"
)

func RepositoryLoggingMiddleware() middleware.Middleware[Repository] {
	logger := slog.Default().With(slog.String("service", "inventory"))
	return func(next Repository) Repository {
		return &repositoryLoggingService{Repository: next, next: next, logger: logger}
	}
}

type repositoryLoggingService struct {
	Repository // forwards methods that cannot be decorated
	next       Repository
	logger     *slog.Logger
}

func (l *repositoryLoggingService) Close() error {
	l.logger.Debug("Close started")
	err := l.next.Close()
	if err != nil {
		l.logger.Error("Close failed", slog.Any("error", err))
	}
	return err
}

func (l *repositoryLoggingService) Get(ctx context.Context, sku string) (*Item, error) {
	l.logger.DebugContext(ctx, "Get started", slog.Any("sku", sku))
	r0, err := l.next.Get(ctx, sku)
	if err != nil {
		l.logger.ErrorContext(ctx, "Get failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) List(ctx context.Context) ([]Item, error) {
	l.logger.DebugContext(ctx, "List started")
	r0, err := l.next.List(ctx)
	if err != nil {
		l.logger.ErrorContext(ctx, "List failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) Save(ctx context.Context, item *Item) (*Item, error) {
	l.logger.DebugContext(ctx, "Save started", slog.Any("item", item))
	r0, err := l.next.Save(ctx, item)
	if err != nil {
		l.logger.ErrorContext(ctx, "Save failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) Merge(ctx context.Context, from *Item, into *Item) (*Item, error) {
	l.logger.DebugContext(ctx, "Merge started", slog.Any("from", from), slog.Any("into", into))
	r0, err := l.next.Merge(ctx, from, into)
	if err != nil {
		l.logger.ErrorContext(ctx, "Merge failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) Archive(ctx context.Context, item *Item) (*Item, error) {
	l.logger.DebugContext(ctx, "Archive started", slog.Any("item", item))
	r0, err := l.next.Archive(ctx, item)
	if err != nil {
		l.logger.ErrorContext(ctx, "Archive failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) RotateKey(ctx context.Context, sku string, key string) error {
	l.logger.DebugContext(ctx, "RotateKey started", slog.Any("sku", sku), slog.String("key", "[REDACTED]"))
	err := l.next.RotateKey(ctx, sku, key)
	if err != nil {
		l.logger.ErrorContext(ctx, "RotateKey failed", slog.Any("error", err))
	}
	return err
}

func (l *repositoryLoggingService) Decrement(ctx context.Context, sku string, qty int) (int, error) {
	l.logger.DebugContext(ctx, "Decrement started", slog.Any("sku", sku), slog.Any("qty", qty))
	r0, err := l.next.Decrement(ctx, sku, qty)
	if err != nil {
		l.logger.ErrorContext(ctx, "Decrement failed", slog.Any("error", err))
	}
	return r0, err
}
