// Code generated by middlegen. DO NOT EDIT.
package ledger

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"github.com/pobochiigo/silo/uow"
)

func RepositoryUoWMiddleware() middleware.Middleware[Repository] {
	return func(next Repository) Repository {
		return &repositoryUoWMiddleware{Repository: next, next: next}
	}
}

type repositoryUoWMiddleware struct {
	Repository // forwards methods that cannot be decorated
	next       Repository
}

func (m *repositoryUoWMiddleware) GetAccount(ctx context.Context, id string) (*Account, error) {
	return m.next.GetAccount(ctx, id)
}

func (m *repositoryUoWMiddleware) ListEntries(ctx context.Context, accountID string, limit int) ([]Entry, error) {
	return m.next.ListEntries(ctx, accountID, limit)
}

func (m *repositoryUoWMiddleware) CreateAccount(ctx context.Context, acc *Account) (*Account, error) {
	if uowInstance, ok := uow.Extract(ctx); ok {
		uowInstance.Defer(func(txCtx context.Context) error {
			_, err := m.next.CreateAccount(txCtx, acc)
			return err
		})
		return acc, nil
	}
	return m.next.CreateAccount(ctx, acc)
}

func (m *repositoryUoWMiddleware) AddEntry(ctx context.Context, entry *Entry) (*Entry, error) {
	if uowInstance, ok := uow.Extract(ctx); ok {
		uowInstance.Defer(func(txCtx context.Context) error {
			_, err := m.next.AddEntry(txCtx, entry)
			return err
		})
		return entry, nil
	}
	return m.next.AddEntry(ctx, entry)
}

func (m *repositoryUoWMiddleware) AdjustBalance(ctx context.Context, id string, delta int64) error {
	if uowInstance, ok := uow.Extract(ctx); ok {
		uowInstance.Defer(func(txCtx context.Context) error {
			return m.next.AdjustBalance(txCtx, id, delta)
		})
		return nil
	}
	return m.next.AdjustBalance(ctx, id, delta)
}
