// Code generated by middlegen. DO NOT EDIT.
package ledger

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"log/slog"
)

func RepositoryLoggingMiddleware() middleware.Middleware[Repository] {
	logger := slog.Default().With(slog.String("service", "ledger"))
	return func(next Repository) Repository {
		return &repositoryLoggingService{Repository: next, next: next, logger: logger}
	}
}

type repositoryLoggingService struct {
	Repository // forwards methods that cannot be decorated
	next       Repository
	logger     *slog.Logger
}

func (l *repositoryLoggingService) GetAccount(ctx context.Context, id string) (*Account, error) {
	l.logger.DebugContext(ctx, "GetAccount started", slog.Any("id", id))
	r0, err := l.next.GetAccount(ctx, id)
	if err != nil {
		l.logger.ErrorContext(ctx, "GetAccount failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) ListEntries(ctx context.Context, accountID string, limit int) ([]Entry, error) {
	l.logger.DebugContext(ctx, "ListEntries started", slog.Any("accountID", accountID), slog.Any("limit", limit))
	r0, err := l.next.ListEntries(ctx, accountID, limit)
	if err != nil {
		l.logger.ErrorContext(ctx, "ListEntries failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) CreateAccount(ctx context.Context, acc *Account) (*Account, error) {
	l.logger.DebugContext(ctx, "CreateAccount started", slog.Any("acc", acc))
	r0, err := l.next.CreateAccount(ctx, acc)
	if err != nil {
		l.logger.ErrorContext(ctx, "CreateAccount failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) AddEntry(ctx context.Context, entry *Entry) (*Entry, error) {
	l.logger.DebugContext(ctx, "AddEntry started", slog.Any("entry", entry))
	r0, err := l.next.AddEntry(ctx, entry)
	if err != nil {
		l.logger.ErrorContext(ctx, "AddEntry failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *repositoryLoggingService) AdjustBalance(ctx context.Context, id string, delta int64) error {
	l.logger.DebugContext(ctx, "AdjustBalance started", slog.Any("id", id), slog.Any("delta", delta))
	err := l.next.AdjustBalance(ctx, id, delta)
	if err != nil {
		l.logger.ErrorContext(ctx, "AdjustBalance failed", slog.Any("error", err))
	}
	return err
}
