// Code generated by middlegen. DO NOT EDIT.
package ledger

import (
	"context"
	"fmt"
	"time"

	"github.com/pobochiigo/silo/middleware"
	"github.com/pobochiigo/silo/telemetry"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

func RepositoryMetricsMiddleware() middleware.Middleware[Repository] {
	meter := otel.GetMeterProvider().Meter("ledger")
	recorder := telemetry.NewMetricsRecorder(meter, "repository")
	ledgerAccountsCreatedTotalCounter, err := recorder.Meter().Int64Counter("ledger_accounts_created_total", metric.WithDescription("Custom counter for ledger_accounts_created_total"))
	if err != nil {
		otel.Handle(err)
	}
	return func(next Repository) Repository {
		return &repositoryMetricsService{
			Repository:                        next,
			next:                              next,
			recorder:                          recorder,
			ledgerAccountsCreatedTotalCounter: ledgerAccountsCreatedTotalCounter,
		}
	}
}

type repositoryMetricsService struct {
	Repository                        // forwards methods that cannot be decorated
	next                              Repository
	recorder                          *telemetry.MetricsRecorder
	ledgerAccountsCreatedTotalCounter metric.Int64Counter
}

func (m *repositoryMetricsService) GetAccount(ctx context.Context, id string) (*Account, error) {
	now := time.Now()
	r0, err := m.next.GetAccount(ctx, id)
	m.recorder.Observe(ctx, "GetAccount", now, err)
	return r0, err
}

func (m *repositoryMetricsService) ListEntries(ctx context.Context, accountID string, limit int) ([]Entry, error) {
	now := time.Now()
	r0, err := m.next.ListEntries(ctx, accountID, limit)
	m.recorder.Observe(ctx, "ListEntries", now, err)
	return r0, err
}

func (m *repositoryMetricsService) CreateAccount(ctx context.Context, acc *Account) (*Account, error) {
	now := time.Now()
	m.ledgerAccountsCreatedTotalCounter.Add(ctx, 1)
	r0, err := m.next.CreateAccount(ctx, acc)
	m.recorder.Observe(ctx, "CreateAccount", now, err)
	return r0, err
}

func (m *repositoryMetricsService) AddEntry(ctx context.Context, entry *Entry) (*Entry, error) {
	now := time.Now()
	r0, err := m.next.AddEntry(ctx, entry)
	m.recorder.Observe(ctx, "AddEntry", now, err)
	return r0, err
}

func (m *repositoryMetricsService) AdjustBalance(ctx context.Context, id string, delta int64) error {
	now := time.Now()
	err := m.next.AdjustBalance(ctx, id, delta)
	m.recorder.Observe(ctx, "AdjustBalance", now, err, attribute.String("direction", fmt.Sprintf("%v", direction(delta))))
	return err
}
