// Code generated by middlegen. DO NOT EDIT.
package ledger

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func RepositoryTracingMiddleware() middleware.Middleware[Repository] {
	tracer := otel.Tracer("ledger")
	return func(next Repository) Repository {
		return &repositoryTracingService{Repository: next, next: next, tracer: tracer}
	}
}

type repositoryTracingService struct {
	Repository // forwards methods that cannot be decorated
	next       Repository
	tracer     trace.Tracer
}

func (t *repositoryTracingService) GetAccount(ctx context.Context, id string) (*Account, error) {
	ctx, span := t.tracer.Start(ctx, "ledger.GetAccount", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.GetAccount(ctx, id)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) ListAccounts(ctx context.Context) ([]Account, error) {
	ctx, span := t.tracer.Start(ctx, "ledger.ListAccounts", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.ListAccounts(ctx)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) ListEntries(ctx context.Context, accountID string, limit int) ([]Entry, error) {
	ctx, span := t.tracer.Start(ctx, "ledger.ListEntries", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.ListEntries(ctx, accountID, limit)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) CreateAccount(ctx context.Context, acc *Account) (*Account, error) {
	ctx, span := t.tracer.Start(ctx, "ledger.CreateAccount", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.CreateAccount(ctx, acc)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) AddEntry(ctx context.Context, entry *Entry) (*Entry, error) {
	ctx, span := t.tracer.Start(ctx, "ledger.AddEntry", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.AddEntry(ctx, entry)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *repositoryTracingService) AdjustBalance(ctx context.Context, id string, delta int64) error {
	ctx, span := t.tracer.Start(ctx, "ledger.AdjustBalance", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	err := t.next.AdjustBalance(ctx, id, delta)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return err
}
