// Code generated by middlegen. DO NOT EDIT.
package ledger

import (
	"context"

	"github.com/pobochiigo/silo/middleware"
	"github.com/pobochiigo/silo/uow"
)

func ServiceUoWMiddleware(manager *uow.Manager) middleware.Middleware[Service] {
	return func(next Service) Service {
		return &serviceUoWMiddleware{Service: next, next: next, manager: manager}
	}
}

type serviceUoWMiddleware struct {
	Service // forwards methods that cannot be decorated
	next    Service
	manager *uow.Manager
}

func (m *serviceUoWMiddleware) OpenAccount(ctx context.Context, id string, owner string, opening int64) (*Account, error) {
	var (
		r0  *Account
		err error
	)
	err = m.manager.RunWith(ctx, func(uowCtx context.Context) error {
		var innerErr error
		r0, innerErr = m.next.OpenAccount(uowCtx, id, owner, opening)
		return innerErr
	})
	return r0, err
}

func (m *serviceUoWMiddleware) Transfer(ctx context.Context, from string, to string, amount int64) error {
	return m.manager.RunInTx(ctx, func(uowCtx context.Context) error {
		return m.next.Transfer(uowCtx, from, to, amount)
	})
}

func (m *serviceUoWMiddleware) Statement(ctx context.Context, id string) (*Account, []Entry, error) {
	var (
		r0  *Account
		r1  []Entry
		err error
	)
	err = m.manager.RunWith(ctx, func(uowCtx context.Context) error {
		var innerErr error
		r0, r1, innerErr = m.next.Statement(uowCtx, id)
		return innerErr
	})
	return r0, r1, err
}
