// Code generated by middlegen. DO NOT EDIT.
package ledger

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func ServiceTracingMiddleware() middleware.Middleware[Service] {
	tracer := otel.Tracer("ledger")
	return func(next Service) Service {
		return &serviceTracingService{Service: next, next: next, tracer: tracer}
	}
}

type serviceTracingService struct {
	Service // forwards methods that cannot be decorated
	next    Service
	tracer  trace.Tracer
}

func (t *serviceTracingService) OpenAccount(ctx context.Context, id string, owner string, opening int64) (*Account, error) {
	ctx, span := t.tracer.Start(ctx, "ledger.OpenAccount", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, err := t.next.OpenAccount(ctx, id, owner, opening)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, err
}

func (t *serviceTracingService) Transfer(ctx context.Context, from string, to string, amount int64) error {
	ctx, span := t.tracer.Start(ctx, "ledger.Transfer", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	err := t.next.Transfer(ctx, from, to, amount)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return err
}

func (t *serviceTracingService) ApplyInterest(ctx context.Context, rateBps int64) error {
	ctx, span := t.tracer.Start(ctx, "ledger.ApplyInterest", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	err := t.next.ApplyInterest(ctx, rateBps)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return err
}

func (t *serviceTracingService) Statement(ctx context.Context, id string) (*Account, []Entry, error) {
	ctx, span := t.tracer.Start(ctx, "ledger.Statement", trace.WithSpanKind(trace.SpanKindInternal))
	defer span.End()
	r0, r1, err := t.next.Statement(ctx, id)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return r0, r1, err
}
