// Code generated by middlegen. DO NOT EDIT.
package ledger

import (
	"context"
	"github.com/pobochiigo/silo/middleware"
	"log/slog"
)

func ServiceLoggingMiddleware() middleware.Middleware[Service] {
	logger := slog.Default().With(slog.String("service", "ledger"))
	return func(next Service) Service {
		return &serviceLoggingService{Service: next, next: next, logger: logger}
	}
}

type serviceLoggingService struct {
	Service // forwards methods that cannot be decorated
	next    Service
	logger  *slog.Logger
}

func (l *serviceLoggingService) OpenAccount(ctx context.Context, id string, owner string, opening int64) (*Account, error) {
	l.logger.DebugContext(ctx, "OpenAccount started", slog.Any("id", id), slog.Any("owner", owner), slog.Any("opening", opening))
	r0, err := l.next.OpenAccount(ctx, id, owner, opening)
	if err != nil {
		l.logger.ErrorContext(ctx, "OpenAccount failed", slog.Any("error", err))
	}
	return r0, err
}

func (l *serviceLoggingService) Transfer(ctx context.Context, from string, to string, amount int64) error {
	l.logger.DebugContext(ctx, "Transfer started", slog.Any("from", from), slog.Any("to", to), slog.Any("amount", amount))
	err := l.next.Transfer(ctx, from, to, amount)
	if err != nil {
		l.logger.ErrorContext(ctx, "Transfer failed", slog.Any("error", err))
	}
	return err
}

func (l *serviceLoggingService) ApplyInterest(ctx context.Context, rateBps int64) error {
	l.logger.DebugContext(ctx, "ApplyInterest started", slog.Any("rateBps", rateBps))
	err := l.next.ApplyInterest(ctx, rateBps)
	if err != nil {
		l.logger.ErrorContext(ctx, "ApplyInterest failed", slog.Any("error", err))
	}
	return err
}

func (l *serviceLoggingService) Statement(ctx context.Context, id string) (*Account, []Entry, error) {
	l.logger.DebugContext(ctx, "Statement started", slog.Any("id", id))
	r0, r1, err := l.next.Statement(ctx, id)
	if err != nil {
		l.logger.ErrorContext(ctx, "Statement failed", slog.Any("error", err))
	}
	return r0, r1, err
}
